{% set name = "quetz-frontend" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/quetz-frontend/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3a3f87704d2373030da8e6653bb8c3f6547fac6200984c3ffdac804ecff88513

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - nodejs
    - jupyter-packaging
  run:
    - python >=3.6

test:
  imports:
    - quetz_frontend

about:
  home: https://github.com/mamba-org/quetz-frontend
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A frontend for quetz

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
