{% set name = "quetz-frontend" %}
{% set version = "0.4.0a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quetz-frontend-{{ version }}.tar.gz
  sha256: d97497bb805c24446969828ab678f62645fa9ddea7847f8b09ff40b2e73356c9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - quetz-frontend = quetz_frontend.cli:app

requirements:
  host:
    - python >=3.7
    - pip
    - jupyter-packaging
  run:
    - python >=3.7
    - quetz >=0.4.0
    - authlib <1.0.0

test:
  imports:
    - quetz_frontend
  commands:
    - pip check
    - quetz-frontend --help
  requires:
    - pip

about:
  home: https://github.com/mamba-org/quetz-frontend
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A frontend for quetz

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
    - fcollonval
    - hbcarlos
