{% set name = "quetz-frontend" %}
{% set version = "0.1.2" %}
{% set frontend_dir = "share/quetz/frontend" %}  

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/quetz/archive/frontend_v{{ version }}.tar.gz
  sha256: 83d3b20e80646c9147cc96e124395b9f68cfcd0c1108a63fa02fb46d99cc275e

build:
  noarch: generic
  ignore_run_exports:
    - libstdc++
  number: 0
  script: >
    cd quetz_frontend; npm install; npm run build; mkdir -p {{ PREFIX }}/{{ frontend_dir }}; cp -r dist/* {{ PREFIX }}/{{ frontend_dir }};

requirements:
  build:
    - {{ compiler('cxx') }}
    - nodejs
  host:
  run:

test:
  commands:
    - test -f $PREFIX/{{ frontend_dir }}/index.html
    - test `ls -1 $PREFIX/{{ frontend_dir }}/js/ | wc -l` -eq 4

about:
  home: https://github.com/TheSnakePit/quetz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A frontend for quetz

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
