{% set name = "quetz-frontend" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-server/{{ name }}-server-{{ version }}.tar.gz
  sha256: 36010220d2aa908e475ede2cb7ebb4cac80934d1378c55cf5f799b43e62832f6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - nodejs >=12
    - yarn
    - jupyter-packaging
  run:
    - python >=3.6
    - quetz >=0.1.0

test:
  imports:
    - quetz_frontend

about:
  home: https://github.com/mamba-org/quetz-frontend
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A frontend for quetz

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
