{% set name = "quetz-frontend" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quetz-frontend-{{ version }}.tar.gz
  sha256: d1686ab4184ab60346bace56fecfd0608b75eafd985b4640215ff497d936b286

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - quetz-frontend = quetz_frontend.cli:app

requirements:
  host:
    - python >=3.7
    - pip
    - jupyter-packaging
  run:
    - python >=3.7
    - quetz >=0.4.0
    - authlib <1.0.0
    - httpx ~=0.20.0
    - h11 <0.13,>=0.11

test:
  imports:
    - quetz_frontend
  commands:
    - pip check
    - quetz-frontend --help
  requires:
    - pip

about:
  home: https://github.com/mamba-org/quetz-frontend
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A frontend for quetz

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
    - fcollonval
    - hbcarlos
